# Generated by Django 4.0.4 on 2022-04-19 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('start_point', models.CharField(max_length=100)),
                ('base_height', models.IntegerField(default=0)),
                ('min_height', models.IntegerField(default=0)),
                ('max_height', models.IntegerField(default=0)),
                ('pos_elev_gain', models.IntegerField(default=0)),
                ('neg_elev_gain', models.IntegerField(default=0)),
                ('estim_duration', models.DurationField(default=0)),
                ('estim_difficulty', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
