# Generated by Django 4.0.4 on 2022-04-21 07:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='estim_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=datetime.date(2022, 4, 21))),
                ('actual_duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('number_people', models.IntegerField(default=1)),
                ('group_xp', models.CharField(choices=[('B', 'Beginners'), ('E', 'Experienced'), ('M', 'Mixed')], default='B', max_length=1)),
                ('weather', models.CharField(choices=[('G', 'Good'), ('N', 'Neutral'), ('B', 'Bad')], default='N', max_length=1)),
                ('difficulty_felt', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
