# Generated by Django 4.0.4 on 2022-04-21 09:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_alter_itineraire_estim_duration_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='estim_duration',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='actual_duration',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
