# Generated by Django 4.0.4 on 2022-04-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0003_alter_itineraire_estim_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='weather',
            field=models.CharField(choices=[('G', 'Good'), ('N', 'Neutral'), ('B', 'Bad')], default='G', max_length=1),
        ),
    ]
